/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as NovaCallRouteImport } from './routes/nova-call'
import { Route as CallCallIdRouteImport } from './routes/call.$callId'
import { Route as PosCallCallIdRouteImport } from './routes/pos-call.$callId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaCallRoute = NovaCallRouteImport.update({
  id: '/nova-call',
  path: '/nova-call',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCallIdRoute = CallCallIdRouteImport.update({
  id: '/call/$callId',
  path: '/call/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const PosCallCallIdRoute = PosCallCallIdRouteImport.update({
  id: '/pos-call/$callId',
  path: '/pos-call/$callId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/nova-call': typeof NovaCallRoute
  '/call/$callId': typeof CallCallIdRoute
  '/pos-call/$callId': typeof PosCallCallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/nova-call': typeof NovaCallRoute
  '/call/$callId': typeof CallCallIdRoute
  '/pos-call/$callId': typeof PosCallCallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/nova-call': typeof NovaCallRoute
  '/call/$callId': typeof CallCallIdRoute
  '/pos-call/$callId': typeof PosCallCallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/calls' | '/nova-call' | '/call/$callId' | '/pos-call/$callId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calls' | '/nova-call' | '/call/$callId' | '/pos-call/$callId'
  id:
    | '__root__'
    | '/'
    | '/calls'
    | '/nova-call'
    | '/call/$callId'
    | '/pos-call/$callId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallsRoute: typeof CallsRoute
  NovaCallRoute: typeof NovaCallRoute
  CallCallIdRoute: typeof CallCallIdRoute
  PosCallCallIdRoute: typeof PosCallCallIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-call': {
      id: '/nova-call'
      path: '/nova-call'
      fullPath: '/nova-call'
      preLoaderRoute: typeof NovaCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$callId': {
      id: '/call/$callId'
      path: '/call/$callId'
      fullPath: '/call/$callId'
      preLoaderRoute: typeof CallCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-call/$callId': {
      id: '/pos-call/$callId'
      path: '/pos-call/$callId'
      fullPath: '/pos-call/$callId'
      preLoaderRoute: typeof PosCallCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallsRoute: CallsRoute,
  NovaCallRoute: NovaCallRoute,
  CallCallIdRoute: CallCallIdRoute,
  PosCallCallIdRoute: PosCallCallIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
